apiVersion: v1
kind: Pod
metadata:
  name: ftpserver
spec:
  containers:
    - name: ftpserver
      image: 192.168.70.143:5000/ftpserver:1.0
      imagePullPolicy: Always
      ports:
        - name: ftp-listen
          hostPort: 10021
          containerPort: 21
        - name: ftp-passive
          hostPort: 21000
          containerPort: 21000
      env:
        - name: MIN_PORT
          value: "21000"
        - name: MAX_PORT
          value: "21000"
        - name: USERS
          value: "ariel|ariel.1234|/data"
        - name: ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
