## under pv directory must be exist k8s-vm.1/ariel/emgc_dbms k8s-vm.2/ariel/emgc_dbms
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ariel
  name: emgc-dbms-pv0
  labels:
    node_info: k8s-vm.1
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: emgc-dbms-storage
  local:
    path: /ariel/emgc_dbms
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-vm.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ariel
  name: emgc-dbms-pv1
  labels:
    node_info: k8s-vm.2
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: emgc-dbms-storage
  local:
    path: /ariel/emgc_dbms
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-vm.2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ariel
  name: emgc-pvc-emgc-mp-statefulset-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: emgc-dbms-storage
  selector:
    matchLabels:
      node_info: k8s-vm.1
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ariel
  name: emgc-pvc-emgc-mp-statefulset-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: emgc-dbms-storage
  selector:
    matchLabels:
      node_info: k8s-vm.2
  resources:
    requests:
      storage: 2Gi
