## service for static view
apiVersion: v1
kind: Service
metadata:
  namespace: ariel
  name: emgc-mp-service
  labels:
    app: emgc
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: emgc
---
## service for A/S routing
apiVersion: v1
kind: Service
metadata:
  namespace: ariel
  name: emgc-as-service-udp
  annotations:
      metallb.universe.tf/address-pool: emgc-as-service-pool-udp
  labels:
    app: emgc
spec:
  clusterIP: "" # "" means any of CIDR ip address
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app: emgc
    status: active
  externalTrafficPolicy: Local
  ports:
    - name: radius-access-udp
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: radius-account-udp
      protocol: UDP
      port: 1813
      targetPort: 1813
---
## service for A/S routing
apiVersion: v1
kind: Service
metadata:
  namespace: ariel
  name: emgc-as-service-tcp
  annotations:
      metallb.universe.tf/address-pool: emgc-as-service-pool-tcp
  labels:
    app: emgc
spec:
  clusterIP: "" # "" means any of CIDR ip address
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app: emgc
    status: active
  externalTrafficPolicy: Local
  ports:
    - name: emguib-emgu-tcp
      protocol: TCP
      port: 21250
      targetPort: 21250
    - name: restif-http-0-tcp
      protocol: TCP
      port: 12444
      targetPort: 12444
    - name: restif-http-1-tcp
      protocol: TCP
      port: 9401
      targetPort: 9401
    - name: restif-http-2-tcp
      protocol: TCP
      port: 9402
      targetPort: 9402
    - name: ftp-server-tcp
      protocol: TCP
      port: 10021
      targetPort: 21
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ariel
  name: emgc-mp-statefulset
spec:
  selector:
    matchLabels:
      app: emgc
  serviceName: emgc-mp-service
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: emgc-pvc # pvc create name = emgc-pvc - [metadata.name] -0-1-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  template:
    metadata:
      labels:
        app: emgc
        service: emgc-mp-service ## ref headless-svc.metadata.name
        statefulset: emgc-mp-statefulset ## ref Statefulset.metadata.name
    spec:
      securityContext: 
        sysctls:
        - name: kernel.sem
          value: "512 32000 512 4096"
      volumes:
      - name: tmp-sysconfig
        configMap:
          name: emgc-config-map-1.0
      - name: shared-bin
        emptyDir: {}
      - name: shared-data
        emptyDir: {}
      - name: ariel-acc-token
        secret:
          secretName: ariel-secret
      - name: replace-script
        configMap:
          name: replace-script
          defaultMode: 0777
      - name: emgc-init-script
        configMap:
          name: emgc-init-script
          defaultMode: 0777
      - name: nfs-vol
        nfs:
          server: 192.168.70.143
          path: /nfs_data/ariel/emgc
      initContainers:
        - name: init-container-00
          image: 192.168.70.143:5000/busybox:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-bin
              mountPath: "/local/bin"
          command: ["/bin/sh", "-c", "cp /bin/* /local/bin"]
        - name: init-container-01
          image: 192.168.70.143:5000/busybox_bash:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tmp-sysconfig
              mountPath: "/tmp/data"
            - name: shared-data
              mountPath: "/data"
            - name: shared-bin
              mountPath: "/local/bin"
            - name: replace-script
              mountPath: "/replace_script"
            - name: emgc-init-script
              mountPath: "/init_script"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_STATEFUL_SET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['statefulset']
          command: ["/bin/sh", "-c", "/init_script/start.sh"]
      containers:
        - name: altibase
          image: 192.168.70.143:5000/altibase_7.1.0:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: emgc-pvc
            subPathExpr: dbs
            mountPath: /home/altibase/altibase_home/dbs
          - name: emgc-pvc
            subPathExpr: logs
            mountPath: /home/altibase/altibase_home/logs
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: emgc-pvc
            subPathExpr: conf
            mountPath: /home/altibase/altibase_home/conf
          env:
            - name: MODE
              value: "daemon"
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
          livenessProbe:
            failureThreshold: 10
            periodSeconds: 1
            tcpSocket:
              port: 20300
        - name: dbreplica
          image: 192.168.70.143:5000/dbreplica:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/sh", "-c", "source /data/k8s.env;/dbreplica"]
        - name: ftpserver
          image: 192.168.70.143:5000/ftpserver:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          ports:
            - name: ftp-passive
              hostPort: 21000
              containerPort: 21000
          env:
            - name: MIN_PORT
              value: "21000"
            - name: MAX_PORT
              value: "21000"
            - name: USERS
              value: "ariel|ariel.1234|/data"
            - name: ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
        - name: ixpc
          image: 192.168.70.143:5000/ixpc:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/IXPC
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/ixpc"]
        - name: dbm
          image: 192.168.70.143:5000/dbm:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/DBM
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/dbm"]
        - name: acntif
          image: 192.168.70.143:5000/acntif:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/ACNTIF
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/acntif"]
        - name: restif
          image: 192.168.70.143:5000/restif:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/RESTIF
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/restif_mkdir.sh;/usr/local/tomcat/bin/startup.sh;tail -f /dev/null"]
        - name: provib
          image: 192.168.70.143:5000/provib:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/PROVIB
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/provib"]
        - name: authif
          image: 192.168.70.143:5000/authif:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/AUTHIF
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/entry.sh;/authif"]
        - name: ftpib
          image: 192.168.70.143:5000/ftpib:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/FTPIB
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/ftpib"]
        - name: emguib
          image: 192.168.70.143:5000/emguib:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/EMGUIB
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/emguib"]
        - name: logd
          image: 192.168.70.143:5000/logd:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/LOGD
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;/logd_mkdir.sh;/logd"]
        - name: reportd
          image: 192.168.70.143:5000/reportd:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: emgc-pvc
            subPathExpr: trc
            mountPath: /home/altibase/altibase_home/trc
          - name: nfs-vol
            subPathExpr: $(MY_POD_NAME)/CONFIG
            mountPath: /data/CONFIG
          env:
            - name: ALTIBASE_HOME
              value: "/home/altibase/altibase_home"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/REPORTD
              port: 32768
          command: ["/bin/sh", "-c", "source /data/k8s.env;mkdir -p /log/SESS_USAGE;/reportd"]
        - name: k8smgr
          image: 192.168.70.143:5000/k8smgr:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-data
            mountPath: "/data"
          - name: shared-bin
            mountPath: "/bin"
          - name: ariel-acc-token
            mountPath: "/k8s/secret"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/K8SMGR
              port: 32768
          command: ["/k8smgr"]
