apiVersion: v1
kind: Pod
metadata:
  name: scpclient
spec:
  containers:
    - name: scpclient
      image: 192.168.70.143:5000/scpclient:1.0
      imagePullPolicy: Always
      command: ["sh", "-c", "tail -f /dev/null"]
