apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-curl
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-vm.1
  containers:
    - name: curl
      image: curlimages/curl:7.75.0
      imagePullPolicy: Always
      command: ["sh", "-c", "tail -f /dev/null"]
