apiVersion: v1
kind: Service
metadata:
  name: k8s-test-svc
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 12345
      name: named-port
      targetPort: 12345
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-k8smgr
  labels:
    app: server
spec:
  volumes:
    - name: data-sysconfig
      configMap:
        name: config-data-dir
    - name: proc-status
      emptyDir: {}
  containers:
    - name: busybox-container
      image: 192.168.70.143:5000/busybox:1.0
      imagePullPolicy: Always
      volumeMounts:
        - name: data-sysconfig
          mountPath: "/pod/data"
        - name: proc-status
          mountPath: "/pod/proc"
      startupProbe:
        exec:
          command: ["cat", "/pod/proc/pod.startup"]
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 1
        exec:
          command: ["cat", "/pod/proc/ready.test"]
      livenessProbe:
        initialDelaySeconds: 5
        periodSeconds: 1
        exec:
          command: ["cat", "/pod/proc/K8SMGR.live"]
      command: ["sh", "-c", "tail -f /dev/null"]
    - name: proca
      image: 192.168.70.143:5000/proc_a:1.0
      imagePullPolicy: Always
      env:
        - name: IV_HOME
          value: "/"
      volumeMounts:
        - name: data-sysconfig
          mountPath: "/data"
      command: ["/proc_a"]
    - name: procb
      image: 192.168.70.143:5000/proc_b:1.0
      imagePullPolicy: Always
      env:
        - name: IV_HOME
          value: "/"
      volumeMounts:
        - name: data-sysconfig
          mountPath: "/data"
      command: ["/proc_b"]
    - name: k8smgr
      image: 192.168.70.143:5000/k8smgr:1.0
      imagePullPolicy: Always
      env:
        - name: IV_HOME
          value: "/"
      volumeMounts:
        - name: data-sysconfig
          mountPath: "/data"
        - name: proc-status
          mountPath: "/pod/proc"
      command: ["/k8smgr"]
