apiVersion: v1
kind: Pod
metadata:
  name: k8s-test-01
spec:
  volumes:
  - name: shared-bin
    emptyDir: {}
  initContainers:
    - name: init-container
      image: 192.168.70.143:5000/busybox:1.0
      imagePullPolicy: Always
      command: ["/bin/sh", "-c", "cp /bin/* /usr/local/bin"]
      volumeMounts:
      - name: shared-bin
        mountPath: /usr/local/bin
  containers:
    - name: test-container
      image: 192.168.70.143:5000/hello_client:1.0
      imagePullPolicy: Always
      command: ["/bin/sh", "-c", "while true; do echo hello; sleep 10; done"]
      volumeMounts:
      - name: shared-bin
        mountPath: /bin
