apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-test-nfs-vol-stateful
spec:
  selector:
    matchLabels:
      app: k8s-test-nfs-stateful
  serviceName: "k8s-nfs-test"
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-test-nfs-stateful
    spec:
      volumes:
      - name: nfs-vol
        nfs:
          server: 192.168.70.143
          path: /nfs_data
      containers:
        - name: test-container
          image: 192.168.70.143:5000/busybox:1.0
          imagePullPolicy: Always
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          volumeMounts:
          - name: nfs-vol
            subPathExpr: $(POD_NAME)/hello # create /nfs/data/$(POD_NAME:k8s-test-08), if non-exist
            mountPath: /data1
          command: ["sh", "-c", "tail -f /dev/null"]
