apiVersion: v1
kind: Service
metadata:
  name: k8s-svc-k8smgr
  labels:
    app: k8s-app-k8smgr
spec:
  clusterIP: None
  selector:
    app: k8s-app-k8smgr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-stateful-k8smgr
spec:
  selector:
    matchLabels:
      app: k8s-app-k8smgr
  serviceName: k8s-svc-k8smgr
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-app-k8smgr
        name: MP
        type: FEP
        group: K8S_TEST
    spec:
      volumes:
      - name: tmp-sysconfig
        configMap:
          name: config-data-dir
      - name: label-conf
        downwardAPI:
          items:
            - path: name
              fieldRef:
                fieldPath: metadata.labels['name']
            - path: type
              fieldRef:
                fieldPath: metadata.labels['type']
            - path: group
              fieldRef:
                fieldPath: metadata.labels['group']
      - name: shared-data
        emptyDir: {}
      initContainers:
        - name: init-container
          image: 192.168.70.143:5000/busybox:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tmp-sysconfig
              mountPath: "/tmp/data"
            - name: shared-data
              mountPath: "/data"
          command: ["/bin/sh", "-c", "cp /tmp/data/* /data"]
      containers:
        - name: topo
          image: 192.168.70.143:5000/topo:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: label-conf
              mountPath: "/label_conf"
            - name: shared-data
              mountPath: "/data"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: EMS_TOPO_ADDR
              valueFrom:
                configMapKeyRef:
                  name: config-test-map.v1
                  key: EMS_TOPO_ADDR
          command: ["/topo"]
        - name: k8smgr
          image: 192.168.70.143:5000/k8smgr:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: label-conf
              mountPath: "/label_conf"
            - name: shared-data
              mountPath: "/data"
          env:
            - name: IV_HOME
              value: "/"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 1
            httpGet:
              path: /start
              port: 32768
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /ready
              port: 32768
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/K8SMGR
              port: 32768
          command: ["/k8smgr"]
        - name: proca
          image: 192.168.70.143:5000/proc_a:1.0
          imagePullPolicy: Always
          env:
            - name: IV_HOME
              value: "/"
          volumeMounts:
            - name: shared-data
              mountPath: "/data"
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/PROC_A
              port: 32768
          command: ["/proc_a"]
        - name: procb
          image: 192.168.70.143:5000/proc_b:1.0
          imagePullPolicy: Always
          env:
            - name: IV_HOME
              value: "/"
          volumeMounts:
            - name: shared-data
              mountPath: "/data"
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/PROC_B
              port: 32768
          command: ["/proc_b"]
