apiVersion: v1
kind: ConfigMap
metadata:
  name: config-data-dir
  namespace: default
data:
  sysconfig: |
    [GENERAL]
    MP_LABEL     = K8SF

    [APPLICATIONS]
    #name   =   where       alarm_level                 msgQkey     msgQkey_2   msgQkey_3   msgQkey_4
    #                   (1:minor, 2:major, 3:critical)
    #-------------------------------------------------------------------------------------------------
    PROC_A   =  bin/proc_a      3                       0x75000     NULL        NULL
    PROC_B   =  bin/proc_b      3                       0x75001     NULL        NULL
    K8SMGR   =  bin/k8smgr      3                       0x75002     NULL        NULL

    [SHARED_MEMORY_KEY]
    SHM_KEEPALIVE       = 0x93000

  EMS_TOPO_ADDR: 192.168.70.143:8000

  # AA (All Active) AS (Active-Standby) SA (Standby-Active)
  AS_MODE: AA
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-svc-k8smgr
  labels:
    app: k8s-app-k8smgr
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: k8s-app-k8smgr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-stateful-k8smgr
spec:
  selector:
    matchLabels:
      app: k8s-app-k8smgr
  serviceName: k8s-svc-k8smgr
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-app-k8smgr
        service: k8s-svc-k8smgr
    spec:
      volumes:
      - name: tmp-sysconfig
        configMap:
          name: config-data-dir
      - name: shared-data
        emptyDir: {}
      initContainers:
        - name: init-container
          image: 192.168.70.143:5000/busybox:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: tmp-sysconfig
              mountPath: "/tmp/data"
            - name: shared-data
              mountPath: "/data"
          command: ["/bin/sh", "-c", "cp /tmp/data/* /data"]
      containers:
        - name: k8smgr
          image: 192.168.70.143:5000/k8smgr:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: "/data"
          env:
            - name: IV_HOME
              value: "/"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 1
            httpGet:
              path: /start
              port: 32768
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /ready
              port: 32768
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/K8SMGR
              port: 32768
          command: ["/k8smgr"]
        - name: proca
          image: 192.168.70.143:5000/proc_a:1.0
          imagePullPolicy: Always
          env:
            - name: IV_HOME
              value: "/"
          volumeMounts:
            - name: shared-data
              mountPath: "/data"
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/PROC_A
              port: 32768
          command: ["/proc_a"]
        - name: procb
          image: 192.168.70.143:5000/proc_b:1.0
          imagePullPolicy: Always
          env:
            - name: IV_HOME
              value: "/"
          volumeMounts:
            - name: shared-data
              mountPath: "/data"
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 1
            httpGet:
              path: /live/PROC_B
              port: 32768
          command: ["/proc_b"]
