apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-at-specific-node
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce   # volume read/write by single node
  # - ReadOnlyMany  # read-only by many node
  # - ReadWriteMany # read/write by many node
  persistentVolumeReclaimPolicy: Retain # Retain(remain) Delete(remove immediately) Recycle(deprecated)
  storageClassName: pv-test-storage-class
  local:
    path: /disk_pv_test
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-vm.1 # create pv at hostname match with k8s-vm.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvclaim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: pv-test-storage-class
  resources:
    requests:
      storage: 100M
