---
apiVersion: v1
kind: Namespace
metadata:
  name: ariel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ariel-sa
  namespace: ariel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ariel-role
  namespace: ariel
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ariel-rolebinding
  namespace: ariel
subjects:
- kind: ServiceAccount
  name: ariel-sa
  namespace: ariel
roleRef:
  kind: Role
  name: ariel-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: ariel-secret
  namespace: ariel
  annotations:
    kubernetes.io/service-account.name: ariel-sa
type: kubernetes.io/service-account-token
