apiVersion: v1
kind: Pod
metadata:
  namespace: ariel
  name: k8s-test-tcpdump
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-vm.1
  containers:
    - name: test-container-0
      image: 192.168.70.143:5000/tcpdump:1.0
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "tail -f /dev/null"]
