apiVersion: v1
kind: Pod
metadata:
  namespace: ariel
  name: k8s-test
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-vm.1
  volumes:
  - name: ariel-secret
    secret:
      secretName: ariel-secret
  containers:
    - name: test-container-0
      image: 192.168.70.143:5000/busybox:1.0
      imagePullPolicy: Always
      volumeMounts:
      - name: ariel-secret
        mountPath: "/k8s/secret"
      command: ["sh", "-c", "tail -f /dev/null"]
