apiVersion: v1
kind: Pod
metadata:
  name: k8s-busybox-bash
spec:
  containers:
    - name: test-container-0
      image: bgruening/busybox-bash:latest
      imagePullPolicy: Always
      command: ["sh", "-c", "tail -f /dev/null"]
