apiVersion: v1
kind: Service
metadata:
  name: metal-lb-00
spec:
  type: LoadBalancer
  ports:
  - name: lb-a
    protocol: TCP
    port: 30000
    nodePort: 30000
    targetPort: 80
  selector:
    app: nginx
  externalTrafficPolicy: Local
#  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 192.168.70.143:5000/tcpdump:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        command: ["sh", "-c", "tail -f /dev/null"]
