apiVersion: v1
kind: Service
metadata:
  name: metal-lb-00
spec:
  ports:
  - name: lb-a
    protocol: TCP
    port: 30000
    nodePort: 30000
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
