#!/bin/bash

### check argc
if [ "$#" -ne 2 ];then
    echo usage} "$0 image_name tag_info"
    exit
fi
image_name="$1"
tag_info="$2"

### get env REGISTRY_INFO
registry_info=`echo $REGISTRY_INFO`
if [ -z ${registry_info} ];then
    echo "< [REGISTRY_INFO] env not setted, proc fail!>"
    exit
fi
echo "registry_info[${registry_info}]"
echo ""

curl -ski -X GET https://${registry_info}/v2/${image_name}/manifests/${tag_info} -H "Accept: application/vnd.docker.distribution.manifest.v2+json" | grep -i "docker-content-digest" | awk '{ print $2 }'
